# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

- name: Add HashiCorp GPG Key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  tags: hashi

#--> not useing command to get dist info. using facts and variables instead.
- name: Add HashiCorp Linux Repository
  apt_repository:
    repo: deb https://apt.releases.hashicorp.com {{ansible_lsb.codename}} main
    state: present
  tags: hashi

- name: Update apt and install HashiCorp
  apt: update_cache=yes name={{item}} state=latest
  loop:
    - consul-enterprise
    - nomad-enterprise
    - vault-enterprise
  tags: hashi
